# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.cache/wt [current_project]
set_property parent.project_path C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8/memfile.dat
read_verilog -library xil_defaultlib {
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/first_lab.srcs/sources_1/new/Accelerator.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/first_lab.srcs/sources_1/new/BUF.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/first_lab.srcs/sources_1/new/CMP.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/first_lab.srcs/sources_1/new/CNT.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/first_lab.srcs/sources_1/new/CU.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/first_lab.srcs/sources_1/new/DP.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/new/EXE_to_MEM_stage.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/new/ID_to_EXE_stage.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/new/IF_to_ID_stage.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/new/MEM_to_WB_stage.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/first_lab.srcs/sources_1/new/MUL.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/new/MUL_op.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/first_lab.srcs/sources_1/new/MUX.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/first_lab.srcs/sources_1/new/REG.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/new/ad_top.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/PATCHED_MIPS_single_cycle/single_cycle_mips_source_initial/datapath/adder.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/PATCHED_MIPS_single_cycle/single_cycle_mips_source_initial/datapath/alu.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/PATCHED_MIPS_single_cycle/single_cycle_mips_source_initial/control_unit/auxdec.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/PATCHED_MIPS_single_cycle/validation_wrapper/button_debouncer.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/PATCHED_MIPS_single_cycle/validation_wrapper/clk_gen.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/PATCHED_MIPS_single_cycle/single_cycle_mips_source_initial/control_unit/controlunit.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/PATCHED_MIPS_single_cycle/single_cycle_mips_source_initial/datapath/datapath.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/PATCHED_MIPS_single_cycle/single_cycle_mips_source_initial/memory/dmem.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/PATCHED_MIPS_single_cycle/single_cycle_mips_source_initial/datapath/dreg.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/new/fact_ad.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/new/fact_reg.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/new/fact_top.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/new/four2one_mux.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/new/gpio_ad.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/new/gpio_top.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/PATCHED_MIPS_single_cycle/validation_wrapper/hex_to_7seg.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/PATCHED_MIPS_single_cycle/single_cycle_mips_source_initial/memory/imem.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/PATCHED_MIPS_single_cycle/validation_wrapper/led_mux.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/PATCHED_MIPS_single_cycle/single_cycle_mips_source_initial/control_unit/maindec.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/PATCHED_MIPS_single_cycle/single_cycle_mips_source_initial/mips/mips.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/PATCHED_MIPS_single_cycle/single_cycle_mips_source_initial/mips/mips_top.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/new/mips_top_4_to_1_mux.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/PATCHED_MIPS_single_cycle/single_cycle_mips_source_initial/datapath/mux2.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/PATCHED_MIPS_single_cycle/single_cycle_mips_source_initial/datapath/regfile.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/PATCHED_MIPS_single_cycle/single_cycle_mips_source_initial/datapath/signext.v
  C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/sources_1/imports/lab8_week3.srcs/sources_1/imports/PATCHED_MIPS_single_cycle/validation_wrapper/mips_fpga.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/constrs_1/imports/validation_wrapper/mips_fpga.xdc
set_property used_in_implementation false [get_files C:/Users/chris/Desktop/CMPE140/LAB/lab8/lab8_week4/lab8_week4/lab8_week4.srcs/constrs_1/imports/validation_wrapper/mips_fpga.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top mips_fpga -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mips_fpga.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mips_fpga_utilization_synth.rpt -pb mips_fpga_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
